VERSION="2.0"

[[CURRENCIES]]
code = "EHP"
issuer = "GAKD... (GAKDI5CTLJ7MJUK57YGPJWYIC2AFA2HJOGGTBMMYGPVSZT7FXR77J3NU)"
display_decimals = 2
name = "Ehaberian Pound"
desc = "Official currency of the Kingdom of Ehaberia"
image = "https://github.com/Ehaberia/eh-stellar/blob/main/WhatsApp%20Image%202025-03-20%20at%2006.29.16_d9727e56.jpg?raw=true"
